_wandb:
    value:
        cli_version: 0.21.0
        e:
            c93ug1t9osrcuqtq0ejdmlmmxk2ma4q5:
                args:
                    - --config
                    - configs/teacher_large.yaml
                    - --wandb
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "41922560000"
                        used: "18534932480"
                email: advaitgupta@ymail.com
                executable: /cmlscratch/advait25/drone_transformer_rl/drone_venv/bin/python
                git:
                    commit: f35d9719f166972f33f09dbea91468bdf9231c39
                    remote: git@github.com:MatthewDulcich/DeepLearning612.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6f4ee91b-c955-4f27-347a-7c71f06219f8
                host: cml31.umiacs.umd.edu
                memory:
                    total: "404901859328"
                os: Linux-4.18.0-553.62.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: -m drone_rl.train.train
                python: CPython 3.11.2
                root: /cmlscratch/advait25/drone_transformer_rl
                slurm:
                    cluster_name: nexus
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: cml-zhou
                    job_cpus_per_node: "8"
                    job_end_time: "1753258225"
                    job_gid: "17634"
                    job_gpus: "0"
                    job_id: "4832611"
                    job_name: teacher-train
                    job_nodelist: cml31
                    job_num_nodes: "1"
                    job_partition: cml-zhou
                    job_qos: cml-high
                    job_start_time: "1753243825"
                    job_uid: "17634"
                    job_user: advait25
                    jobid: "4832611"
                    localid: "0"
                    mem_per_node: "131072"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: cml31
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    submit_dir: /cmlscratch/advait25/drone_transformer_rl
                    submit_host: nexuscml01.umiacs.umd.edu
                    task_pid: "395772"
                    tasks_per_node: "1"
                    topology_addr: cml31
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                startedAt: "2025-07-23T04:10:32.636414Z"
                writerId: c93ug1t9osrcuqtq0ejdmlmmxk2ma4q5
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 35
            "4": 3.11.2
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
env_id:
    value: FlyCraft-v0
eval_freq:
    value: 20000
max_episode_steps:
    value: 1000
n_envs:
    value: 16
n_eval_episodes:
    value: 10
output_dir:
    value: runs
policy:
    value: transformer
policy_kwargs:
    value:
        log_std_init: -1.5
        transformer_kwargs:
            depth: 8
            dropout: 0.1
            embed_dim: 512
            memory_size: 128
            num_heads: 16
            proj_out_dim: 256
ppo_kwargs:
    value:
        batch_size: 4096
        clip_range: 0.2
        clip_range_vf: 0.2
        ent_coef: 0.01
        gae_lambda: 0.95
        gamma: 0.997
        learning_rate: 0.0001
        max_grad_norm: 0.5
        n_epochs: 4
        n_steps: 2048
        target_kl: null
        vf_coef: 0.5
predict_sequence:
    value: true
prediction_horizon:
    value: 200
run_name:
    value: teacher_large_v5
save_freq:
    value: 50000
seed:
    value: 42
timesteps:
    value: 5000000
use_spatio_temporal:
    value: true
