_current_progress_remaining:
    value: 1
_custom_logger:
    value: "True"
_episode_num:
    value: 0
_last_episode_starts:
    value: |-
        [ True  True  True  True  True  True  True  True  True  True  True  True
          True  True  True  True]
_last_obs:
    value: |-
        {'achieved_goal': array([[2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00],
               [2.0000000e+02, 5.0888877e-16, 0.0000000e+00]], dtype=float32), 'desired_goal': array([[ 239.4736   ,  -73.04808  ,  171.22404  ],
               [ 267.84253  ,   15.685748 ,  -99.10612  ],
               [ 293.8368   ,  -60.782917 ,  128.62572  ],
               [ 262.33856  ,    1.8411939,  100.56228  ],
               [ 224.3701   ,   78.125114 , -149.41916  ],
               [ 120.745    ,   84.03333  ,  -64.529884 ],
               [ 238.89838  ,   27.449415 ,  130.72205  ],
               [ 224.73985  ,   28.046642 , -175.10909  ],
               [ 294.68982  ,  -47.36996  ,   52.892403 ],
               [ 144.52371  ,   51.516758 , -101.98511  ],
               [ 101.27791  ,    9.05263  ,  168.60184  ],
               [ 286.61774  ,  -71.13154  ,   59.91719  ],
               [ 215.48795  ,  -74.49833  ,  -16.095789 ],
               [ 146.01942  ,   -1.3062421,   91.16025  ],
               [ 244.92084  ,    7.9581885,  -95.176674 ],
               [ 168.06396  ,  -19.112114 , -123.680885 ]], dtype=float32), 'observation': array([[0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03],
               [0.0000000e+00, 2.6132205e+00, 0.0000000e+00, 2.0000000e+02,
                5.0888877e-16, 0.0000000e+00, 0.0000000e+00, 5.0000000e+03]],
              dtype=float32)}
_last_original_obs:
    value: None
_logger:
    value: <stable_baselines3.common.logger.Logger object at 0x7f0e3dd8a750>
_n_updates:
    value: 0
_num_timesteps_at_start:
    value: 0
_stats_window_size:
    value: 100
_total_timesteps:
    value: 5000000
_vec_normalize_env:
    value: None
_wandb:
    value:
        cli_version: 0.21.0
        e:
            sskodsreyzol2t4au8oo8x6aer223aau:
                args:
                    - --config
                    - configs/teacher_large.yaml
                    - --wandb
                cpu_count: 32
                cpu_count_logical: 64
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "41922560000"
                        used: "18534395904"
                email: advaitgupta@ymail.com
                executable: /cmlscratch/advait25/drone_transformer_rl/drone_venv/bin/python
                git:
                    commit: b24cf592a023b0995cf4c417c40aba9cf7a6bb38
                    remote: git@github.com:MatthewDulcich/DeepLearning612.git
                gpu: NVIDIA A100 80GB PCIe
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6912
                      memoryTotal: "85899345920"
                      name: NVIDIA A100 80GB PCIe
                      uuid: GPU-6f4ee91b-c955-4f27-347a-7c71f06219f8
                host: cml31.umiacs.umd.edu
                memory:
                    total: "404901859328"
                os: Linux-4.18.0-553.62.1.el8_10.x86_64-x86_64-with-glibc2.28
                program: -m drone_rl.train.train
                python: CPython 3.11.2
                root: /cmlscratch/advait25/drone_transformer_rl
                slurm:
                    cluster_name: nexus
                    conf: /etc/slurm/slurm.conf
                    cpus_on_node: "8"
                    cpus_per_task: "8"
                    distribution: block
                    gpus_on_node: "1"
                    gtids: "0"
                    job_account: cml-zhou
                    job_cpus_per_node: "8"
                    job_end_time: "1753247849"
                    job_gid: "17634"
                    job_group: advait25
                    job_id: "4832429"
                    job_name: bash
                    job_nodelist: cml31
                    job_num_nodes: "1"
                    job_partition: cml-zhou
                    job_qos: cml-medium
                    job_start_time: "1753233449"
                    job_uid: "17634"
                    job_user: advait25
                    jobid: "4832429"
                    launch_node_ipaddr: 128.8.121.79
                    localid: "0"
                    mem_per_node: "65536"
                    nnodes: "1"
                    nodeid: "0"
                    nodelist: cml31
                    nprocs: "1"
                    ntasks: "1"
                    oom_kill_step: "0"
                    prio_process: "0"
                    procid: "0"
                    pty_port: "41135"
                    pty_win_col: "66"
                    pty_win_row: "15"
                    srun_comm_host: 128.8.121.79
                    srun_comm_port: "35297"
                    step_gpus: "0"
                    step_id: "0"
                    step_launcher_port: "35297"
                    step_nodelist: cml31
                    step_num_nodes: "1"
                    step_num_tasks: "1"
                    step_tasks_per_node: "1"
                    stepid: "0"
                    submit_dir: /cmlscratch/advait25
                    submit_host: nexuscml01.umiacs.umd.edu
                    task_pid: "379508"
                    tasks_per_node: "1"
                    topology_addr: cml31
                    topology_addr_pattern: node
                    tres_per_task: cpu=8
                    umask: "0002"
                startedAt: "2025-07-23T03:12:13.640069Z"
                writerId: sskodsreyzol2t4au8oo8x6aer223aau
        m: []
        python_version: 3.11.2
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 13
                - 16
                - 22
                - 35
            "4": 3.11.2
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
action_noise:
    value: None
action_space:
    value: Box([-180.   -4.    0.], [180.   9.   1.], (3,), float32)
algo:
    value: PPO
batch_size:
    value: 4096
clip_range:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7f0e3ddd7c40>
clip_range_vf:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7f0e3ddd7d80>
device:
    value: cuda
ent_coef:
    value: 0.01
env:
    value: <stable_baselines3.common.vec_env.vec_monitor.VecMonitor object at 0x7f0e3ddcd5d0>
env_id:
    value: FlyCraft-v0
ep_info_buffer:
    value: deque([], maxlen=100)
ep_success_buffer:
    value: deque([], maxlen=100)
eval_freq:
    value: 20000
gae_lambda:
    value: 0.95
gamma:
    value: 0.997
learning_rate:
    value: 0.0001
lr_schedule:
    value: <function get_schedule_fn.<locals>.<lambda> at 0x7f0e3ddd79c0>
max_episode_steps:
    value: 1000
max_grad_norm:
    value: 0.5
n_envs:
    value: 16
n_epochs:
    value: 4
n_eval_episodes:
    value: 10
n_steps:
    value: 2048
normalize_advantage:
    value: "True"
num_timesteps:
    value: 0
observation_space:
    value: 'Dict(''achieved_goal'': Box([   0.  -90. -180.], [1000.   90.  180.], (3,), float32), ''desired_goal'': Box([   0.  -90. -180.], [1000.   90.  180.], (3,), float32), ''observation'': Box([-180.  -90. -180.    0.  -90. -180. -300.    0.], [  180.    90.   180.  1000.    90.   180.   300. 20000.], (8,), float32))'
output_dir:
    value: runs
policy:
    value: transformer
policy_class:
    value: <class 'drone_rl.models.transformer_policy.TransformerActorCritic'>
policy_kwargs:
    value:
        log_std_init: -2
        transformer_kwargs:
            depth: 8
            dropout: 0.1
            embed_dim: 512
            memory_size: 128
            num_heads: 16
            proj_out_dim: 256
ppo_kwargs:
    value:
        batch_size: 4096
        clip_range: 0.2
        clip_range_vf: 0.2
        ent_coef: 0.01
        gae_lambda: 0.95
        gamma: 0.997
        learning_rate: 0.0001
        max_grad_norm: 0.5
        n_epochs: 4
        n_steps: 2048
        target_kl: 0.03
        vf_coef: 0.5
predict_sequence:
    value: true
prediction_horizon:
    value: 200
rollout_buffer:
    value: <stable_baselines3.common.buffers.DictRolloutBuffer object at 0x7f0e487d3fd0>
rollout_buffer_class:
    value: <class 'stable_baselines3.common.buffers.DictRolloutBuffer'>
rollout_buffer_kwargs:
    value: '{}'
run_name:
    value: teacher_large_v5
save_freq:
    value: 50000
sde_sample_freq:
    value: -1
seed:
    value: 42
start_time:
    value: 1753240348695386959
target_kl:
    value: 0.03
tensorboard_log:
    value: runs/teacher_large_v5/tb
timesteps:
    value: 5000000
use_sde:
    value: "False"
use_spatio_temporal:
    value: true
verbose:
    value: 1
vf_coef:
    value: 0.5
