env_id: FlyCraft-v0
eval_freq: 5000  # More frequent evaluation
n_envs: 8
output_dir: runs
policy: lstm
policy_kwargs:
  lstm_hidden: 256
  lstm_layers: 2
  dropout: 0.1  # Add dropout for regularization
  n_envs: 8
ppo_kwargs:
  batch_size: 512  # Smaller batch size for better gradients
  clip_range: 0.2
  gae_lambda: 0.95
  gamma: 0.99  # Slightly lower discount for more immediate learning
  learning_rate: 0.0001  # Lower learning rate for LSTM stability
  n_epochs: 10  # More epochs per batch for better learning
  n_steps: 512  # Shorter rollouts for better LSTM training
  ent_coef: 0.01  # Encourage exploration
  vf_coef: 0.5  # Balance value function learning
  max_grad_norm: 0.5  # Gradient clipping for LSTM stability
run_name: baseline_lstm_improved
save_freq: 10000
seed: 42
timesteps: 200000  # More training steps

# Additional parameters for better LSTM training
curriculum_learning: true
curriculum_steps: [10, 20, 50]  # Hz frequencies
curriculum_timesteps: [50000, 100000, 200000]

# Environment parameters
max_episode_steps: 1000
n_eval_episodes: 10
