# LSTM with 200-step predictor - SINGLE FREQUENCY (no curriculum blocking)
env_id: FlyCraft-v0
run_name: lstm_predictor_single_50hz_h200
output_dir: runs
seed: 42

# Training at single frequency (50Hz)
frequency: 50  # Bypass curriculum, train only at 50Hz

# Production scale
n_envs: 8
max_episode_steps: 1000

# LSTM policy with larger capacity for 200-step prediction
policy: lstm
policy_kwargs:
  lstm_hidden: 256    # Larger for 200-step prediction task
  lstm_layers: 2
  dropout: 0.1

# PPO settings optimized for longer training
ppo_kwargs:
  n_steps: 1024       
  batch_size: 512     
  n_epochs: 4
  learning_rate: 3.0e-4
  gamma: 0.997        
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

# Long training duration at single frequency
timesteps: 2_000_000  # All timesteps at 50Hz

# Regular monitoring
save_freq: 100_000
eval_freq: 50_000
n_eval_episodes: 10

# Full 200-step prediction horizon
predict_sequence: true
prediction_horizon: 200

# Single frequency settings
goal_cfg: {"type": "fixed_short", "distance_m": 200}  # Standard goal
control_mode: "guidance_law_mode"
reward_mode: "dense"
