# LSTM with 5-step future predictor - validation config
env_id: FlyCraft-v0
run_name: lstm_predictor_test
output_dir: runs
seed: 42

# Moderate scale for proper testing
n_envs: 4
max_episode_steps: 500

# LSTM policy
policy: lstm
policy_kwargs:
  lstm_hidden: 128
  lstm_layers: 2
  dropout: 0.1

# PPO settings - better for longer training
ppo_kwargs:
  n_steps: 512     # More steps per rollout
  batch_size: 256  # Reasonable batch size
  n_epochs: 4      # More epochs for better learning
  learning_rate: 3.0e-4
  gamma: 0.99
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

# Longer training to see predictor effects
timesteps: 250_000

# Reasonable monitoring
save_freq: 25_000
eval_freq: 12_500
n_eval_episodes: 5

# Enable future predictor with small horizon for testing
predict_sequence: true
prediction_horizon: 5  # Start small, then scale to 200

# Easier curriculum progression for early training
goal_cfg_by_freq:
  "10": {"type": "fixed_short", "distance_m": 100}   # Start easier
  "20": {"type": "fixed_short", "distance_m": 150}   # Gradual increase  
  "50": {"type": "fixed_short", "distance_m": 200}   # Standard
  "100": {"type": "fixed_medium", "distance_m": 300} # More challenging
