# LSTM with 50-step predictor - SINGLE FREQUENCY (no curriculum blocking)
env_id: FlyCraft-v0
run_name: lstm_predictor_single_50hz_h50
output_dir: runs
seed: 42

# Training at single frequency (50Hz)
frequency: 50  # Bypass curriculum, train only at 50Hz

# Medium scale
n_envs: 6
max_episode_steps: 750

# LSTM policy 
policy: lstm
policy_kwargs:
  lstm_hidden: 192
  lstm_layers: 2
  dropout: 0.1

# PPO settings
ppo_kwargs:
  n_steps: 768
  batch_size: 384
  n_epochs: 4
  learning_rate: 3.0e-4
  gamma: 0.995        
  gae_lambda: 0.95
  clip_range: 0.2
  ent_coef: 0.01
  vf_coef: 0.5
  max_grad_norm: 0.5

# Full training duration at single frequency
timesteps: 1_000_000  # All timesteps at 50Hz

# Regular checkpoints
save_freq: 50_000
eval_freq: 25_000
n_eval_episodes: 8

# Medium horizon prediction
predict_sequence: true
prediction_horizon: 50

# Single frequency settings
goal_cfg: {"type": "fixed_short", "distance_m": 150}  # Reasonable goal
control_mode: "guidance_law_mode"
reward_mode: "dense"
